version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
     - postgis-data:/var/lib/postgresql
    environment:
     - POSTGRES_DB=gis
     - POSTGRES_USER=gis_admin
     - POSTGRES_PASS=admin
     - POSTGRES_DBNAME=gis
    ports:
     - 5434:5432
    restart: on-failure

volumes:
 postgis-data: