version: "3"

volumes:
  postgis-data:

# Networks to be created to facilitate communication between containers
networks:
  app-network:
    driver: bridge

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network
    environment:
      - DB_HOST=db
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - app-network
